In [27]:
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd

In [28]:
teams_info = teams.get_teams()
teams_df = pd.DataFrame(teams_info)
teams_df.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [ ]:
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable='2014')
games = gamefinder.get_data_frames()
print(games[0].iloc[0])

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [21]:
df.columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [23]:
df['expected_min'] = df['MIN'] / df['GP']
df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,expected_min
0,252,1985-86,00,1610612762,UTH,22.0,81,76,2475,504,...,174,544,718,236,105,44,279,295,1203,30.555556
1,252,1986-87,00,1610612762,UTH,23.0,82,82,2857,728,...,278,577,855,158,104,60,237,323,1779,34.841463
2,252,1987-88,00,1610612762,UTH,24.0,82,82,3198,858,...,277,709,986,199,117,50,325,296,2268,39.000000
3,252,1988-89,00,1610612762,UTH,25.0,80,80,3126,809,...,259,594,853,219,144,70,285,286,2326,39.075000
4,252,1989-90,00,1610612762,UTH,26.0,82,82,3122,914,...,232,679,911,226,121,50,304,259,2540,38.073171
5,252,1990-91,00,1610612762,UTH,27.0,82,82,3302,847,...,236,731,967,270,89,79,244,268,2382,40.268293
6,252,1991-92,00,1610612762,UTH,28.0,81,81,3054,798,...,225,684,909,241,108,51,248,226,2272,37.703704
7,252,1992-93,00,1610612762,UTH,29.0,82,82,3099,797,...,227,692,919,308,124,85,240,261,2217,37.792683
8,252,1993-94,00,1610612762,UTH,30.0,82,82,3329,772,...,235,705,940,328,125,126,234,268,2063,40.597561
9,252,1994-95,00,1610612762,UTH,31.0,82,82,3126,830,...,156,715,871,285,129,85,236,269,2187,38.121951
10,252,1995-96,00,1610612762,UTH,32.0,82,82,3113,789,...,175,629,804,345,138,56,199,245,2106,37.963415
11,252,1996-97,00,1610612762,UTA,33.0,82,82,2998,864,...,193,616,809,368,113,48,233,217,2249,36.560976
12,252,1997-98,00,1610612762,UTA,34.0,81,81,3030,780,...,189,645,834,316,96,70,247,237,2190,37.407407
13,252,1998-99,00,1610612762,UTA,35.0,49,49,1832,393,...,107,356,463,201,62,28,162,134,1164,37.387755
14,252,1999-00,00,1610612762,UTA,36.0,82,82,2947,752,...,169,610,779,304,79,71,231,229,2095,35.939024
15,252,2000-01,00,1610612762,UTA,37.0,81,81,2895,670,...,114,555,669,361,93,62,244,216,1878,35.740741
16,252,2001-02,00,1610612762,UTA,38.0,80,80,3040,635,...,142,544,686,341,152,59,263,229,1788,38.000000
17,252,2002-03,00,1610612762,UTA,39.0,81,81,2936,595,...,113,515,628,379,136,31,210,204,1667,36.246914
18,252,2003-04,00,1610612747,LAL,40.0,42,42,1373,193,...,61,306,367,163,50,20,103,116,554,32.690476

In [27]:
df['expected_ast'] = df['AST'] / df['MIN']
df

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,expected_min,expected_ast
0,252,1985-86,00,1610612762,UTH,22.0,81,76,2475,504,...,544,718,236,105,44,279,295,1203,30.555556,0.095354
1,252,1986-87,00,1610612762,UTH,23.0,82,82,2857,728,...,577,855,158,104,60,237,323,1779,34.841463,0.055303
2,252,1987-88,00,1610612762,UTH,24.0,82,82,3198,858,...,709,986,199,117,50,325,296,2268,39.000000,0.062226
3,252,1988-89,00,1610612762,UTH,25.0,80,80,3126,809,...,594,853,219,144,70,285,286,2326,39.075000,0.070058
4,252,1989-90,00,1610612762,UTH,26.0,82,82,3122,914,...,679,911,226,121,50,304,259,2540,38.073171,0.072389
5,252,1990-91,00,1610612762,UTH,27.0,82,82,3302,847,...,731,967,270,89,79,244,268,2382,40.268293,0.081769
6,252,1991-92,00,1610612762,UTH,28.0,81,81,3054,798,...,684,909,241,108,51,248,226,2272,37.703704,0.078913
7,252,1992-93,00,1610612762,UTH,29.0,82,82,3099,797,...,692,919,308,124,85,240,261,2217,37.792683,0.099387
8,252,1993-94,00,1610612762,UTH,30.0,82,82,3329,772,...,705,940,328,125,126,234,268,2063,40.597561,0.098528
9,252,1994-95,00,1610612762,UTH,31.0,82,82,3126,830,...,715,871,285,129,85,236,269,2187,38.121951,0.091171
10,252,1995-96,00,1610612762,UTH,32.0,82,82,3113,789,...,629,804,345,138,56,199,245,2106,37.963415,0.110826
11,252,1996-97,00,1610612762,UTA,33.0,82,82,2998,864,...,616,809,368,113,48,233,217,2249,36.560976,0.122748
12,252,1997-98,00,1610612762,UTA,34.0,81,81,3030,780,...,645,834,316,96,70,247,237,2190,37.407407,0.104290
13,252,1998-99,00,1610612762,UTA,35.0,49,49,1832,393,...,356,463,201,62,28,162,134,1164,37.387755,0.109716
14,252,1999-00,00,1610612762,UTA,36.0,82,82,2947,752,...,610,779,304,79,71,231,229,2095,35.939024,0.103156
15,252,2000-01,00,1610612762,UTA,37.0,81,81,2895,670,...,555,669,361,93,62,244,216,1878,35.740741,0.124698
16,252,2001-02,00,1610612762,UTA,38.0,80,80,3040,635,...,544,686,341,152,59,263,229,1788,38.000000,0.112171
17,252,2002-03,00,1610612762,UTA,39.0,81,81,2936,595,...,515,628,379,136,31,210,204,1667,36.246914,0.129087
18,252,2003-04,00,1610612747,LAL,40.0,42,42,1373,193,...,306,367,163,50,20,103,116,554,32.690476,0.118718

- combine offensive and defensive into mean?
- use