In [71]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [72]:
import duckdb
import pandas as pd
from src.possession_parser import Possession_parser

In [2]:
con = duckdb.connect(database='data/nba.sqlite', read_only=False)
# df = con.query("show tables").fetchdf()
# df

In [ ]:
## get game-ids

# df = con.query("select * from play_by_play limit 2").fetchdf()
# df

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,0029600012,0,12,0,1,14:43 PM,12:00,None,Start of 1st Period (14:43 PM EST),None,...,None,None,0.0,0,None,None,None,None,None,0
1,0029600012,2,10,0,1,14:50 PM,12:00,Jump Ball O'Neal vs. Kleine: Tip to Cassell,None,None,...,Suns,PHX,5.0,208,Sam Cassell,1610612756.0,Phoenix,Suns,PHX,0

In [ ]:
# df = con.query("select * from play_by_play where game_id = '0029600012'").fetchdf()

In [3]:
game_ids_df = con.query("select distinct game_id from play_by_play").fetchdf()
game_ids = game_ids_df['game_id']

In [57]:
cur_game_id = game_ids[0]
game_df = con.query(f"select * from play_by_play where game_id = '{cur_game_id}'").fetchdf()
game_df = game_df.sort_values(by='eventnum')
game_df

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,0029600064,1,10,0,1,11:40 PM,12:00,Jump Ball Geiger vs. Baker: Tip to Robinson,None,None,...,Bucks,MIL,5.0,299,Glenn Robinson,1610612749.0,Milwaukee,Bucks,MIL,0
1,0029600064,2,2,5,1,11:41 PM,11:45,None,None,MISS Baker Layup,...,None,None,0.0,0,None,None,None,None,None,0
2,0029600064,3,4,0,1,11:41 PM,11:45,None,None,Bucks Rebound,...,None,None,0.0,0,None,None,None,None,None,0
3,0029600064,4,2,5,1,11:41 PM,11:41,None,None,MISS Allen Layup,...,None,None,0.0,0,None,None,None,None,None,0
4,0029600064,5,4,0,1,11:41 PM,11:40,Mason REBOUND (Off:0 Def:1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,0029600064,444,5,1,4,13:59 PM,0:08,Geiger STEAL (1 STL),None,Robinson Bad Pass Turnover (P4.T12),...,Hornets,CHH,0.0,0,None,None,None,None,None,0
442,0029600064,445,2,1,4,13:59 PM,0:01,MISS Rice 3PT Jump Shot,None,None,...,None,None,0.0,0,None,None,None,None,None,0
443,0029600064,446,4,0,4,13:59 PM,0:00,Mason REBOUND (Off:3 Def:9),None,None,...,None,None,0.0,0,None,None,None,None,None,0
444,0029600064,447,9,1,4,13:59 PM,0:00,HORNETS Timeout: Regular (Full 7 Short 2),None,None,...,None,None,0.0,0,None,None,None,None,None,0
445,0029600064,448,13,0,4,14:01 PM,0:00,None,End of 4th Period (14:01 PM EST),None,...,None,None,0.0,0,None,None,None,None,None,0

In [96]:
print(game_df.iloc[123])

game_id                                            0029600064
eventnum                                                  124
eventmsgtype                                                5
eventmsgactiontype                                          2
period                                                      2
wctimestring                                         12:12 PM
pctimestring                                             9:50
homedescription                           Curry STEAL (1 STL)
neutraldescription                                       None
visitordescription           Baker Lost Ball Turnover (P1.T4)
score                                                    None
scoremargin                                              None
person1type                                               5.0
player1_id                                                452
player1_name                                        Vin Baker
player1_team_id                                  1610612749.0
player1_team_city                                   Milwaukee
player1_team_nickname                                   Bucks
player1_team_abbreviation                                 MIL
person2type                                               4.0
player2_id                                                209
player2_name                                       Dell Curry
player2_team_id                                  1610612766.0
player2_team_city                                   Charlotte
player2_team_nickname                                 Hornets
player2_team_abbreviation                                 CHH
person3type                                               0.0
player3_id                                                  0
player3_name                                             None
player3_team_id                                          None
player3_team_city                                        None
player3_team_nickname                                    None
player3_team_abbreviation                                None
video_available_flag                                        0
Name: 123, dtype: object

In [83]:
parser = Possession_parser(game_df)
possessions = parser.parse_game()
possessions

timeout
player not on offense scored at row 45
player not on offense scored at row 61
subbing: 5 players on team0
player not on offense scored at row 68
player not on offense scored at row 69
player not on offense scored at row 70
timeout
subbing: 5 players on team0
subbing: 5 players on team0
subbing: 5 players on team0
subbing: 5 players on team1
player not on offense scored at row 95
player not on offense scored at row 96
subbing: 5 players on team1
end of period
subbing: 5 players on team1
timeout
subbing: 5 players on team1
subbing: 5 players on team0
subbing: 5 players on team1
subbing: 5 players on team0
too many players on team1 @ row 129
too many players on team1 @ row 130
too many players on team1 @ row 131
too many players on team1 @ row 132
too many players on team1 @ row 133
too many players on team1 @ row 134
too many players on team1 @ row 135
too many players on team1 @ row 136
too many players on team1 @ row 137
too many players on team1 @ row 138
too many players on team1 @ row 139
too many players on team1 @ row 140
too many players on team1 @ row 141
too many players on team1 @ row 142
too many players on team1 @ row 143
too many players on team1 @ row 144
too many players on team1 @ row 145
too many players on team1 @ row 146
too many players on team1 @ row 147
too many players on team1 @ row 148
too many players on team1 @ row 149
too many players on team1 @ row 150
timeout
too many players on team1 @ row 151
too many players on team1 @ row 152
too many players on team1 @ row 153
too many players on team1 @ row 154
too many players on team1 @ row 155
too many players on team1 @ row 156
too many players on team1 @ row 157
too many players on team1 @ row 159
too many players on team1 @ row 158
too many players on team1 @ row 160
too many players on team1 @ row 162
too many players on team1 @ row 161
too many players on team1 @ row 163
too many players on team1 @ row 164
too many players on team1 @ row 165
too many players on team1 @ row 166
too many players on team1 @ row 167
too many players on team1 @ row 168
too many players on team1 @ row 169
too many players on team1 @ row 170
too many players on team1 @ row 171
too many players on team1 @ row 172
too many players on team1 @ row 173
too many players on team1 @ row 174
timeout
subbing: 6 players on team1
too many players on team1 @ row 176
too many players on team1 @ row 177
too many players on team1 @ row 178
too many players on team1 @ row 179
too many players on team1 @ row 180
subbing: 6 players on team1
too many players on team1 @ row 182
too many players on team1 @ row 183
too many players on team1 @ row 184
too many players on team1 @ row 185
too many players on team1 @ row 186
too many players on team1 @ row 187
too many players on team1 @ row 188
too many players on team1 @ row 189
too many players on team1 @ row 190
timeout
too many players on team1 @ row 191
too many players on team1 @ row 192
subbing: 6 players on team1
too many players on team1 @ row 194
too many players on team1 @ row 195
too many players on team1 @ row 197
player not on offense scored at row 197
too many players on team1 @ row 196
too many players on team1 @ row 198
too many players on team1 @ row 199
too many players on team1 @ row 200
player not on offense scored at row 200
too many players on team1 @ row 201
too many players on team1 @ row 202
too many players on team1 @ row 203
too many players on team1 @ row 204
too many players on team1 @ row 205
too many players on team1 @ row 206
too many players on team1 @ row 207
too many players on team1 @ row 208
too many players on team1 @ row 209
too many players on team1 @ row 210
too many players on team1 @ row 211
too many players on team1 @ row 212
too many players on team1 @ row 213
too many players on team1 @ row 214
end of period
too many players on team1 @ row 215
too many players on team0 @ row 216
too many players on team1 @ row 216
too many players on team0 @ row 217
too many players on team1 @ row 217
too many players on team0 @ row 218
too many players on team1 @ row 218
too many players on team0 @ row 219
too many players on team1 @ row 219
too many players on team0 @ row 220
too many players on team1 @ row 220
too many players on team0 @ row 221
too many players on team1 @ row 221
too many players on team0 @ row 222
too many players on team1 @ row 222
too many players on team0 @ row 223
too many players on team1 @ row 223
too many players on team0 @ row 224
too many players on team1 @ row 224
too many players on team0 @ row 225
too many players on team1 @ row 225
timeout
too many players on team0 @ row 226
too many players on team1 @ row 226
too many players on team0 @ row 227
too many players on team1 @ row 227
too many players on team0 @ row 228
too many players on team1 @ row 228
too many players on team0 @ row 229
too many players on team1 @ row 229
too many players on team0 @ row 230
too many players on team1 @ row 230
too many players on team0 @ row 231
too many players on team1 @ row 231
too many players on team0 @ row 232
too many players on team1 @ row 232
too many players on team0 @ row 233
too many players on team1 @ row 233
player not on offense scored at row 233
too many players on team0 @ row 234
too many players on team1 @ row 234
too many players on team0 @ row 235
too many players on team1 @ row 235
too many players on team0 @ row 236
too many players on team1 @ row 236
too many players on team0 @ row 237
too many players on team1 @ row 237
too many players on team0 @ row 238
too many players on team1 @ row 238
too many players on team0 @ row 239
too many players on team1 @ row 239
too many players on team0 @ row 240
too many players on team1 @ row 240
too many players on team0 @ row 241
too many players on team1 @ row 241
too many players on team0 @ row 242
too many players on team1 @ row 242
too many players on team0 @ row 243
too many players on team1 @ row 243
too many players on team0 @ row 244
too many players on team1 @ row 244
subbing: 7 players on team0
too many players on team0 @ row 246
too many players on team1 @ row 246
too many players on team0 @ row 247
too many players on team1 @ row 247
too many players on team0 @ row 248
too many players on team1 @ row 248
too many players on team0 @ row 249
too many players on team1 @ row 249
too many players on team0 @ row 250
too many players on team1 @ row 250
too many players on team0 @ row 251
too many players on team1 @ row 251
too many players on team0 @ row 252
too many players on team1 @ row 252
too many players on team0 @ row 253
too many players on team1 @ row 253
too many players on team0 @ row 254
too many players on team1 @ row 254
too many players on team0 @ row 255
too many players on team1 @ row 255
too many players on team0 @ row 256
too many players on team1 @ row 256
too many players on team0 @ row 257
too many players on team1 @ row 257
too many players on team0 @ row 258
too many players on team1 @ row 258
too many players on team0 @ row 259
too many players on team1 @ row 259
too many players on team0 @ row 260
too many players on team1 @ row 260
too many players on team0 @ row 261
too many players on team1 @ row 261
too many players on team0 @ row 262
too many players on team1 @ row 262
timeout
too many players on team0 @ row 263
too many players on team1 @ row 263
too many players on team0 @ row 264
too many players on team1 @ row 264
too many players on team0 @ row 265
too many players on team1 @ row 265
too many players on team0 @ row 266
too many players on team1 @ row 266
too many players on team0 @ row 267
too many players on team1 @ row 267
too many players on team0 @ row 268
too many players on team1 @ row 268
too many players on team0 @ row 269
too many players on team1 @ row 269
too many players on team0 @ row 270
too many players on team1 @ row 270
too many players on team0 @ row 271
too many players on team1 @ row 271
too many players on team0 @ row 272
too many players on team1 @ row 272
too many players on team0 @ row 273
too many players on team1 @ row 273
too many players on team0 @ row 274
too many players on team1 @ row 274
too many players on team0 @ row 275
too many players on team1 @ row 275
timeout
subbing: 7 players on team0
subbing: 8 players on team1
too many players on team0 @ row 278
too many players on team1 @ row 278
too many players on team0 @ row 279
too many players on team1 @ row 279
too many players on team0 @ row 280
too many players on team1 @ row 280
too many players on team0 @ row 281
too many players on team1 @ row 281
too many players on team0 @ row 282
too many players on team1 @ row 282
too many players on team0 @ row 283
too many players on team1 @ row 283
too many players on team0 @ row 285
too many players on team1 @ row 285
too many players on team0 @ row 284
too many players on team1 @ row 284
too many players on team0 @ row 286
too many players on team1 @ row 286
too many players on team0 @ row 287
too many players on team1 @ row 287
too many players on team0 @ row 288
too many players on team1 @ row 288
too many players on team0 @ row 290
too many players on team1 @ row 290
too many players on team0 @ row 289
too many players on team1 @ row 289
too many players on team0 @ row 291
too many players on team1 @ row 291
too many players on team0 @ row 292
too many players on team1 @ row 292
too many players on team0 @ row 293
too many players on team1 @ row 293
too many players on team0 @ row 294
too many players on team1 @ row 294
too many players on team0 @ row 295
too many players on team1 @ row 295
subbing: 7 players on team0
too many players on team0 @ row 297
too many players on team1 @ row 297
too many players on team0 @ row 298
too many players on team1 @ row 298
too many players on team0 @ row 299
too many players on team1 @ row 299
too many players on team0 @ row 300
too many players on team1 @ row 300
too many players on team0 @ row 302
too many players on team1 @ row 302
too many players on team0 @ row 301
too many players on team1 @ row 301
too many players on team0 @ row 303
too many players on team1 @ row 303
too many players on team0 @ row 304
too many players on team1 @ row 304
too many players on team0 @ row 305
too many players on team1 @ row 305
too many players on team0 @ row 306
too many players on team1 @ row 306
too many players on team0 @ row 307
too many players on team1 @ row 307
too many players on team0 @ row 308
too many players on team1 @ row 308
too many players on team0 @ row 309
too many players on team1 @ row 309
too many players on team0 @ row 310
too many players on team1 @ row 310
too many players on team0 @ row 311
too many players on team1 @ row 311
too many players on team0 @ row 312
too many players on team1 @ row 312
too many players on team0 @ row 313
too many players on team1 @ row 313
too many players on team0 @ row 314
too many players on team1 @ row 314
too many players on team0 @ row 315
too many players on team1 @ row 315
too many players on team0 @ row 316
too many players on team1 @ row 316
subbing: 8 players on team1
too many players on team0 @ row 318
too many players on team1 @ row 318
too many players on team0 @ row 319
too many players on team1 @ row 319
too many players on team0 @ row 320
too many players on team1 @ row 320
too many players on team0 @ row 321
too many players on team1 @ row 321
too many players on team0 @ row 322
too many players on team1 @ row 322
too many players on team0 @ row 323
too many players on team1 @ row 323
too many players on team0 @ row 324
too many players on team1 @ row 324
subbing: 7 players on team0
subbing: 7 players on team0
too many players on team0 @ row 327
too many players on team1 @ row 327
too many players on team0 @ row 328
too many players on team1 @ row 328
too many players on team0 @ row 329
too many players on team1 @ row 329
too many players on team0 @ row 331
too many players on team1 @ row 331
player not on offense scored at row 331
too many players on team0 @ row 330
too many players on team1 @ row 330
too many players on team0 @ row 332
too many players on team1 @ row 332
player not on offense scored at row 332
too many players on team0 @ row 333
too many players on team1 @ row 333
end of period
too many players on team0 @ row 334
too many players on team1 @ row 334
too many players on team0 @ row 335
too many players on team1 @ row 335
too many players on team0 @ row 336
too many players on team1 @ row 336
too many players on team0 @ row 337
too many players on team1 @ row 337
too many players on team0 @ row 338
too many players on team1 @ row 338
too many players on team0 @ row 339
too many players on team1 @ row 339
subbing: 8 players on team1
too many players on team0 @ row 341
too many players on team1 @ row 341
too many players on team0 @ row 342
too many players on team1 @ row 342
too many players on team0 @ row 343
too many players on team1 @ row 343
too many players on team0 @ row 344
too many players on team1 @ row 344
too many players on team0 @ row 345
too many players on team1 @ row 345
too many players on team0 @ row 346
too many players on team1 @ row 346
too many players on team0 @ row 347
too many players on team1 @ row 347
too many players on team0 @ row 348
too many players on team1 @ row 348
too many players on team0 @ row 349
too many players on team1 @ row 349
too many players on team0 @ row 350
too many players on team1 @ row 350
too many players on team0 @ row 351
too many players on team1 @ row 351
too many players on team0 @ row 352
too many players on team1 @ row 352
subbing: 9 players on team0
subbing: 9 players on team0
too many players on team0 @ row 355
too many players on team1 @ row 355
too many players on team0 @ row 356
too many players on team1 @ row 356
too many players on team0 @ row 357
too many players on team1 @ row 357
too many players on team0 @ row 358
too many players on team1 @ row 358
too many players on team0 @ row 359
too many players on team1 @ row 359
too many players on team0 @ row 360
too many players on team1 @ row 360
too many players on team0 @ row 361
too many players on team1 @ row 361
timeout
too many players on team0 @ row 362
too many players on team1 @ row 362
too many players on team0 @ row 363
too many players on team1 @ row 363
too many players on team0 @ row 364
too many players on team1 @ row 364
too many players on team0 @ row 365
too many players on team1 @ row 365
too many players on team0 @ row 366
too many players on team1 @ row 366
too many players on team0 @ row 367
too many players on team1 @ row 367
too many players on team0 @ row 368
too many players on team1 @ row 368
too many players on team0 @ row 369
too many players on team1 @ row 369
too many players on team0 @ row 370
too many players on team1 @ row 370
too many players on team0 @ row 371
too many players on team1 @ row 371
too many players on team0 @ row 372
too many players on team1 @ row 372
player not on offense scored at row 372
too many players on team0 @ row 373
too many players on team1 @ row 373
too many players on team0 @ row 375
too many players on team1 @ row 375
too many players on team0 @ row 374
too many players on team1 @ row 374
too many players on team0 @ row 376
too many players on team1 @ row 376
too many players on team0 @ row 377
too many players on team1 @ row 377
too many players on team0 @ row 378
too many players on team1 @ row 378
too many players on team0 @ row 379
too many players on team1 @ row 379
too many players on team0 @ row 380
too many players on team1 @ row 380
too many players on team0 @ row 381
too many players on team1 @ row 381
too many players on team0 @ row 382
too many players on team1 @ row 382
too many players on team0 @ row 383
too many players on team1 @ row 383
timeout
too many players on team0 @ row 384
too many players on team1 @ row 384
too many players on team0 @ row 385
too many players on team1 @ row 385
too many players on team0 @ row 386
too many players on team1 @ row 386
too many players on team0 @ row 387
too many players on team1 @ row 387
too many players on team0 @ row 388
too many players on team1 @ row 388
too many players on team0 @ row 389
too many players on team1 @ row 389
too many players on team0 @ row 390
too many players on team1 @ row 390
too many players on team0 @ row 391
too many players on team1 @ row 391
too many players on team0 @ row 392
too many players on team1 @ row 392
too many players on team0 @ row 393
too many players on team1 @ row 393
too many players on team0 @ row 394
too many players on team1 @ row 394
subbing: 8 players on team1
too many players on team0 @ row 396
too many players on team1 @ row 396
too many players on team0 @ row 397
too many players on team1 @ row 397
too many players on team0 @ row 398
too many players on team1 @ row 398
too many players on team0 @ row 399
too many players on team1 @ row 399
too many players on team0 @ row 400
too many players on team1 @ row 400
too many players on team0 @ row 401
too many players on team1 @ row 401
too many players on team0 @ row 402
too many players on team1 @ row 402
too many players on team0 @ row 403
too many players on team1 @ row 403
too many players on team0 @ row 404
too many players on team1 @ row 404
too many players on team0 @ row 405
too many players on team1 @ row 405
too many players on team0 @ row 406
too many players on team1 @ row 406
too many players on team0 @ row 407
too many players on team1 @ row 407
too many players on team0 @ row 408
too many players on team1 @ row 408
subbing: 9 players on team0
too many players on team0 @ row 410
too many players on team1 @ row 410
too many players on team0 @ row 411
too many players on team1 @ row 411
too many players on team0 @ row 412
too many players on team1 @ row 412
too many players on team0 @ row 413
too many players on team1 @ row 413
timeout
too many players on team0 @ row 414
too many players on team1 @ row 414
too many players on team0 @ row 415
too many players on team1 @ row 415
too many players on team0 @ row 416
too many players on team1 @ row 416
too many players on team0 @ row 417
too many players on team1 @ row 417
too many players on team0 @ row 418
too many players on team1 @ row 418
subbing: 9 players on team0
subbing: 8 players on team1
too many players on team0 @ row 421
too many players on team1 @ row 421
too many players on team0 @ row 422
too many players on team1 @ row 422
too many players on team0 @ row 424
too many players on team1 @ row 424
too many players on team0 @ row 423
too many players on team1 @ row 423
too many players on team0 @ row 425
too many players on team1 @ row 425
player not on offense scored at row 425
too many players on team0 @ row 426
too many players on team1 @ row 426
too many players on team0 @ row 427
too many players on team1 @ row 427
too many players on team0 @ row 428
too many players on team1 @ row 428
timeout
too many players on team0 @ row 429
too many players on team1 @ row 429
too many players on team0 @ row 430
too many players on team1 @ row 430
too many players on team0 @ row 431
too many players on team1 @ row 431
timeout
too many players on team0 @ row 432
too many players on team1 @ row 432
too many players on team0 @ row 433
too many players on team1 @ row 433
too many players on team0 @ row 434
too many players on team1 @ row 434
too many players on team0 @ row 435
too many players on team1 @ row 435
too many players on team0 @ row 436
too many players on team1 @ row 436
too many players on team0 @ row 437
too many players on team1 @ row 437
too many players on team0 @ row 438
too many players on team1 @ row 438
too many players on team0 @ row 439
too many players on team1 @ row 439
timeout
too many players on team0 @ row 440
too many players on team1 @ row 440
timeout
too many players on team0 @ row 441
too many players on team1 @ row 441
too many players on team0 @ row 442
too many players on team1 @ row 442
too many players on team0 @ row 443
too many players on team1 @ row 443
too many players on team0 @ row 444

,game_id,possession_id,offense_team_id,possession_end_event_type,possession_end_points
0,0029600064,0,1610612749.0,4.0,0
1,0029600064,1,1610612766.0,1.5,2
2,0029600064,2,1610612749.0,4.0,0
3,0029600064,3,1610612766.0,4.0,0
4,0029600064,4,1610612749.0,1.1,2
...,...,...,...,...,...
423,0029600064,163,1610612766.0,1.1,2
424,0029600064,164,1610612749.0,5.1,0
425,0029600064,165,1610612766.0,5.1,0
426,0029600064,166,1610612749.0,4.0,0
427,0029600064,167,1610612766.0,13.0,0

In [ ]:
game_df

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag,possession_index
0,0029600310,1,10,0,1,11:39 PM,12:00,Jump Ball Mutombo vs. Williams: Tip to Laettner,None,None,...,PHI,4.0,363,Christian Laettner,1610612737.0,Atlanta,Hawks,ATL,0,0029600310_0
1,0029600310,2,6,2,1,11:40 PM,11:55,None,None,Weatherspoon S.FOUL (P1.T1),...,PHI,0.0,0,None,None,None,None,None,0,0029600310_0
2,0029600310,3,3,11,1,11:40 PM,11:55,MISS Smith Free Throw 1 of 2,None,None,...,None,0.0,0,None,None,None,None,None,0,0029600310_0
3,0029600310,4,4,0,1,11:40 PM,11:55,HAWKS Rebound,None,None,...,None,0.0,0,None,None,None,None,None,0,0029600310_0
4,0029600310,5,3,12,1,11:40 PM,11:55,Smith Free Throw 2 of 2 (1 PTS),None,None,...,None,0.0,0,None,None,None,None,None,0,0029600310_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,0029600310,442,1,5,4,13:41 PM,0:16,None,None,Bradtke Layup (4 PTS) (Harris 1 AST),...,PHI,0.0,0,None,None,None,None,None,0,0029600310_3
433,0029600310,443,5,2,4,13:41 PM,0:10,Barry Lost Ball Turnover (P2.T11),None,None,...,None,0.0,0,None,None,None,None,None,0,0029600310_3
434,0029600310,445,2,1,4,13:41 PM,0:02,None,None,MISS Davis 25' 3PT Jump Shot,...,None,0.0,0,None,None,None,None,None,0,0029600310_3
435,0029600310,446,4,0,4,13:41 PM,0:00,Recasner REBOUND (Off:0 Def:4),None,None,...,None,0.0,0,None,None,None,None,None,0,0029600310_3
436,0029600310,447,13,0,4,13:42 PM,0:00,None,End of 4th Period (13:42 PM EST),None,...,None,0.0,0,None,None,None,None,None,0,0029600310_3

In [ ]:
df[["homedescription",	"neutraldescription"	,"visitordescription"]]

,homedescription,neutraldescription,visitordescription
0,None,Start of 1st Period (14:43 PM EST),None
1,Jump Ball O'Neal vs. Kleine: Tip to Cassell,None,None
2,None,None,MISS Cassell 15' Jump Shot
3,O'Neal REBOUND (Off:0 Def:1),None,None
4,MISS Ceballos 26' 3PT Jump Shot,None,None
...,...,...,...
461,None,None,MISS Manning Free Throw 1 of 2
462,None,None,Suns Rebound
463,None,None,MISS Manning Free Throw 2 of 2
464,Knight REBOUND (Off:0 Def:2),None,None
465,None,End of 4th Period (17:12 PM EST),None

In [ ]:
df.columns

Index(['game_id', 'eventnum', 'eventmsgtype', 'eventmsgactiontype', 'period',
       'wctimestring', 'pctimestring', 'homedescription', 'neutraldescription',
       'visitordescription', 'score', 'scoremargin', 'person1type',
       'player1_id', 'player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation',
       'video_available_flag'],
      dtype='object')

In [ ]:

## Pseudo logic for aggregation of player counting stats


# from collections import Counter

# players = Counter()

# for game in games:
#     for event in game.events:
#         player = event.player
#         stat = event.stat
#         players[player[stat]] += 1