In [30]:
import duckdb
import pandas as pd

In [31]:
con = duckdb.connect(database='../data/nba.sqlite', read_only=False)
df = con.query("show tables").fetchdf()
df

                   name
0    common_player_info
1   draft_combine_stats
2         draft_history
3                  game
4             game_info
5          game_summary
6      inactive_players
7            line_score
8             officials
9           other_stats
10         play_by_play
11               player
12                 team
13         team_details
14         team_history
15     team_info_common

In [32]:
## get game-ids

df = con.query("select * from play_by_play limit 500").fetchdf()
df['game_id'].unique()

array(['0029600012', '0029600005'], dtype=object)

In [33]:
df = con.query("select * from play_by_play where game_id = '0029600005'").fetchdf()

In [34]:
df.head(30)

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,0029600005,1,10,0,1,12:41 PM,12:00,Jump Ball Mourning vs. Mutombo: Tip to Mourning,None,None,...,Hawks,ATL,4.0,297,Alonzo Mourning,1610612748.0,Miami,Heat,MIA,0
1,0029600005,2,6,1,1,12:42 PM,11:51,None,None,Corbin P.FOUL (P1.T1),...,Hawks,ATL,0.0,0,None,None,None,None,None,0
2,0029600005,3,10,0,1,12:43 PM,11:40,Jump Ball Mourning vs. Blaylock: Tip to Hardaway,None,None,...,Hawks,ATL,4.0,896,Tim Hardaway,1610612748.0,Miami,Heat,MIA,0
3,0029600005,4,2,1,1,12:43 PM,11:32,MISS Thomas 9' Jump Shot,None,None,...,None,None,0.0,0,None,None,None,None,None,0
4,0029600005,5,4,0,1,12:43 PM,11:29,Danilovic REBOUND (Off:1 Def:0),None,None,...,None,None,0.0,0,None,None,None,None,None,0
5,0029600005,6,1,1,1,12:43 PM,11:26,Majerle 24' 3PT Jump Shot (3 PTS) (Danilovic 1...,None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
6,0029600005,7,1,6,1,12:43 PM,11:08,None,None,Smith Driving Layup (2 PTS) (Mutombo 1 AST),...,Hawks,ATL,0.0,0,None,None,None,None,None,0
7,0029600005,8,1,1,1,12:44 PM,10:49,Thomas 13' Jump Shot (2 PTS) (Hardaway 1 AST),None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
8,0029600005,9,2,1,1,12:44 PM,10:32,None,None,MISS Smith 17' Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
9,0029600005,10,4,0,1,12:44 PM,10:30,Hardaway REBOUND (Off:0 Def:1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
10,0029600005,11,2,3,1,12:44 PM,10:24,MISS Mourning 5' Hook Shot,None,None,...,None,None,0.0,0,None,None,None,None,None,0
11,0029600005,12,4,0,1,12:44 PM,10:21,None,None,Mutombo REBOUND (Off:0 Def:1),...,None,None,0.0,0,None,None,None,None,None,0
12,0029600005,13,5,2,1,12:44 PM,10:14,Mourning STEAL (1 STL),None,Blaylock Lost Ball Turnover (P1.T1),...,Heat,MIA,0.0,0,None,None,None,None,None,0
13,0029600005,14,1,5,1,12:44 PM,10:09,Mourning Layup (2 PTS) (Hardaway 2 AST),None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
14,0029600005,15,5,1,1,12:45 PM,9:54,Thomas STEAL (1 STL),None,Blaylock Bad Pass Turnover (P2.T2),...,Heat,MIA,0.0,0,None,None,None,None,None,0
15,0029600005,16,5,1,1,12:45 PM,9:49,Thomas Bad Pass Turnover (P1.T1),None,Blaylock STEAL (1 STL),...,Hawks,ATL,0.0,0,None,None,None,None,None,0
16,0029600005,17,1,1,1,12:45 PM,9:38,None,None,Laettner 11' Jump Shot (2 PTS) (Blaylock 1 AST),...,Hawks,ATL,0.0,0,None,None,None,None,None,0
17,0029600005,18,1,1,1,12:45 PM,9:23,Hardaway 3PT Jump Shot (3 PTS) (Majerle 1 AST),None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
18,0029600005,19,9,2,1,12:45 PM,9:17,None,None,Hawks Timeout: Short (Reg.0 Short 1),...,None,None,0.0,0,None,None,None,None,None,0
19,0029600005,20,2,5,1,12:47 PM,8:57,None,None,MISS Smith Layup,...,None,None,0.0,0,None,None,None,None,None,0
20,0029600005,22,4,0,1,12:47 PM,8:56,None,None,Mutombo REBOUND (Off:1 Def:1),...,None,None,0.0,0,None,None,None,None,None,0
21,0029600005,21,2,4,1,12:47 PM,8:56,None,None,MISS Mutombo Tip Shot,...,None,None,0.0,0,None,None,None,None,None,0
22,0029600005,23,4,0,1,12:47 PM,8:54,Thomas REBOUND (Off:0 Def:1),None,None,...,None,None,0.0,0,None,None,None,None,None,0
23,0029600005,24,1,7,1,12:47 PM,8:51,Mourning Dunk (4 PTS) (Danilovic 2 AST),None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
24,0029600005,25,2,1,1,12:47 PM,8:35,None,None,MISS Blaylock 20' Jump Shot,...,None,None,0.0,0,None,None,None,None,None,0
25,0029600005,26,4,0,1,12:47 PM,8:33,None,None,Blaylock REBOUND (Off:1 Def:0),...,None,None,0.0,0,None,None,None,None,None,0
26,0029600005,27,1,8,1,12:47 PM,8:29,None,None,Mutombo Slam Dunk (2 PTS) (Laettner 1 AST),...,Hawks,ATL,0.0,0,None,None,None,None,None,0
27,0029600005,28,1,7,1,12:48 PM,8:06,Mourning Dunk (6 PTS) (Danilovic 3 AST),None,None,...,Heat,MIA,0.0,0,None,None,None,None,None,0
28,0029600005,29,5,4,1,12:48 PM,7:47,None,None,Mutombo Traveling Turnover (P1.T3),...,None,None,0.0,0,None,None,None,None,None,0
29,0029600005,30,2,1,1,12:48 PM,7:24,MISS Mourning 15' Jump Shot,None,None,...,None,None,0.0,0,None,None,None,None,None,0

In [35]:
df.columns

Index(['game_id', 'eventnum', 'eventmsgtype', 'eventmsgactiontype', 'period',
       'wctimestring', 'pctimestring', 'homedescription', 'neutraldescription',
       'visitordescription', 'score', 'scoremargin', 'person1type',
       'player1_id', 'player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation',
       'video_available_flag'],
      dtype='object')

In [36]:
df[[ 'eventnum', 'eventmsgtype', 'eventmsgactiontype',
        'homedescription', 'neutraldescription',
       'visitordescription',  'player1_id', 'player1_name', 'player1_team_id',
       'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 
       'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 
        'player3_team_abbreviation',
    ]].head(5)

,eventnum,eventmsgtype,eventmsgactiontype,homedescription,neutraldescription,visitordescription,player1_id,player1_name,player1_team_id,person2type,player2_id,player2_name,player2_team_id,person3type,player3_id,player3_name,player3_team_id,player3_team_abbreviation
0,1,10,0,Jump Ball Mourning vs. Mutombo: Tip to Mourning,None,None,297,Alonzo Mourning,1610612748.0,5.0,87,Dikembe Mutombo,1610612737.0,4.0,297,Alonzo Mourning,1610612748.0,MIA
1,2,6,1,None,None,Corbin P.FOUL (P1.T1),895,Tyrone Corbin,1610612737.0,5.0,0,None,1610612737.0,0.0,0,None,None,None
2,3,10,0,Jump Ball Mourning vs. Blaylock: Tip to Hardaway,None,None,297,Alonzo Mourning,1610612748.0,5.0,302,Mookie Blaylock,1610612737.0,4.0,896,Tim Hardaway,1610612748.0,MIA
3,4,2,1,MISS Thomas 9' Jump Shot,None,None,703,Kurt Thomas,1610612748.0,0.0,0,None,None,0.0,0,None,None,None
4,5,4,0,Danilovic REBOUND (Off:1 Def:0),None,None,390,Sasha Danilovic,1610612748.0,0.0,0,None,None,0.0,0,None,None,None

In [37]:
df[["homedescription",	"neutraldescription"	,"visitordescription"]]

,homedescription,neutraldescription,visitordescription
0,Jump Ball Mourning vs. Mutombo: Tip to Mourning,None,None
1,None,None,Corbin P.FOUL (P1.T1)
2,Jump Ball Mourning vs. Blaylock: Tip to Hardaway,None,None
3,MISS Thomas 9' Jump Shot,None,None
4,Danilovic REBOUND (Off:1 Def:0),None,None
...,...,...,...
435,Majerle Free Throw 2 of 2 (14 PTS),None,None
436,Hardaway STEAL (3 STL),None,Blaylock Bad Pass Turnover (P7.T24)
437,MISS Majerle 24' 3PT Jump Shot,None,None
438,None,None,Newbill REBOUND (Off:0 Def:4)
439,None,End of 4th Period (14:53 PM EST),None

In [38]:
df.columns

Index(['game_id', 'eventnum', 'eventmsgtype', 'eventmsgactiontype', 'period',
       'wctimestring', 'pctimestring', 'homedescription', 'neutraldescription',
       'visitordescription', 'score', 'scoremargin', 'person1type',
       'player1_id', 'player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation',
       'video_available_flag'],
      dtype='object')

In [39]:

## Pseudo logic for aggregation of player counting stats


# from collections import Counter

# players = Counter()

# for game in games:
#     for event in game.events:
#         player = event.player
#         stat = event.stat
#         players[player[stat]] += 1